### ISSUE TITLE
all gestures other than the zoom are not working

### ISSUE THREAD

**Issue by tasneem151** [yakagami/zoom_view#1]
taps or any type of gestures are not working when using the zoom view widget on a scrollable

**Comment by yakagami** [comment]
I should probably mention that somewhere in the readme. Right now you can't interact with the ListView due to using AbsorbPointer. Once https://github.com/flutter/flutter/pull/136708 is in release it may be possible to remove this limitation, but I have to look at that a bit more closely. So this package right now is mainly only useful for eg. a list of images.

**Comment by yakagami** [comment]
This is now fixed in 0.0.7. @tasneem151 can you confirm?

**Comment by tasneem151** [comment]
@yakagami yes it's working perfectly, thank you.
